<?php $__env->startSection('title','المستخدمون والمسؤولون'); ?>
<?php $__env->startSection('admin-content'); ?>
<div class="admin-page-header mb-4 reveal is-visible"><div class="small text-primary fw-bold mb-1">إدارة الحسابات</div><h1 class="page-heading">المستخدمون والمسؤولون</h1><p class="page-subtitle">إدارة العملاء وتعيين دور «مسؤول طلبات» لمن سيقوم بالمراجعة والمتابعة.</p></div>
<div class="surface-card admin-panel reveal p-3 p-md-4 mb-4"><form method="GET" class="row g-2 align-items-end"><div class="col-md-7 col-xl-5"><label class="form-label">بحث</label><input class="form-control" name="q" value="<?php echo e(request('q')); ?>" placeholder="الاسم / البريد / الهاتف"></div><div class="col-md-auto"><button class="btn btn-primary w-100" type="submit">بحث</button></div><?php if(request()->filled('q')): ?><div class="col-md-auto"><a class="btn btn-outline-secondary w-100" href="<?php echo e(route('admin.users.index')); ?>">مسح</a></div><?php endif; ?></form></div>
<div class="surface-card admin-panel overflow-hidden reveal"><div class="table-responsive"><table class="table table-modern align-middle"><thead><tr><th>الاسم</th><th>البريد</th><th>السلات</th><th>الطلبات</th><th>الدور</th><th>الحالة</th><th></th></tr></thead><tbody>
<?php $__empty_1 = true; $__currentLoopData = $users; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $user): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); $__empty_1 = false; ?><tr><td><div class="d-flex align-items-center gap-2"><span class="avatar-circle border"><?php echo e(mb_substr($user->name,0,1)); ?></span><span class="fw-semibold"><?php echo e($user->name); ?></span></div></td><td class="ltr"><?php echo e($user->email); ?></td><td><?php echo e($user->carts_count); ?></td><td><?php echo e($user->orders_count); ?></td><td><form method="POST" action="<?php echo e(route('admin.users.role',$user)); ?>" class="d-flex gap-1"><?php echo csrf_field(); ?> <?php echo method_field('PATCH'); ?><select name="role" class="form-select form-select-sm" style="min-width:145px"><option value="customer" <?php if($user->role==='customer'): echo 'selected'; endif; ?>>عميل</option><option value="order_manager" <?php if($user->role==='order_manager'): echo 'selected'; endif; ?>>مسؤول طلبات</option></select><button class="btn btn-soft btn-sm">حفظ</button></form></td><td><span class="status-badge <?php echo e($user->is_active?'status-success':'status-danger'); ?>"><?php echo e($user->is_active?'فعال':'موقوف'); ?></span></td><td><form method="POST" action="<?php echo e(route('admin.users.toggle',$user)); ?>"><?php echo csrf_field(); ?> <?php echo method_field('PATCH'); ?><button class="btn btn-soft btn-sm" type="submit"><?php echo e($user->is_active?'إيقاف':'تشغيل'); ?></button></form></td></tr>
<?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); if ($__empty_1): ?><tr><td colspan="7" class="text-center text-secondary py-5">لا توجد نتائج.</td></tr><?php endif; ?>
</tbody></table></div></div><div class="mt-4"><?php echo e($users->links()); ?></div>
<?php $__env->stopSection(); ?>

<?php echo $__env->make('layouts.admin', array_diff_key(get_defined_vars(), ['__data' => 1, '__path' => 1]))->render(); ?><?php /**PATH D:\laragon\www\Salltak\resources\views/admin/users/index.blade.php ENDPATH**/ ?>