@extends('layouts.admin')
@section('title','المستخدمون والمسؤولون')
@section('admin-content')
<div class="admin-page-header mb-4 reveal is-visible"><div class="small text-primary fw-bold mb-1">إدارة الحسابات</div><h1 class="page-heading">المستخدمون والمسؤولون</h1><p class="page-subtitle">إدارة العملاء وتعيين دور «مسؤول طلبات» لمن سيقوم بالمراجعة والمتابعة.</p></div>
<div class="surface-card admin-panel reveal p-3 p-md-4 mb-4"><form method="GET" class="row g-2 align-items-end"><div class="col-md-7 col-xl-5"><label class="form-label">بحث</label><input class="form-control" name="q" value="{{ request('q') }}" placeholder="الاسم / البريد / الهاتف"></div><div class="col-md-auto"><button class="btn btn-primary w-100" type="submit">بحث</button></div>@if(request()->filled('q'))<div class="col-md-auto"><a class="btn btn-outline-secondary w-100" href="{{ route('admin.users.index') }}">مسح</a></div>@endif</form></div>
<div class="surface-card admin-panel overflow-hidden reveal"><div class="table-responsive"><table class="table table-modern align-middle"><thead><tr><th>الاسم</th><th>البريد</th><th>السلات</th><th>الطلبات</th><th>الدور</th><th>الحالة</th><th></th></tr></thead><tbody>
@forelse($users as $user)<tr><td><div class="d-flex align-items-center gap-2"><span class="avatar-circle border">{{ mb_substr($user->name,0,1) }}</span><span class="fw-semibold">{{ $user->name }}</span></div></td><td class="ltr">{{ $user->email }}</td><td>{{ $user->carts_count }}</td><td>{{ $user->orders_count }}</td><td><form method="POST" action="{{ route('admin.users.role',$user) }}" class="d-flex gap-1">@csrf @method('PATCH')<select name="role" class="form-select form-select-sm" style="min-width:145px"><option value="customer" @selected($user->role==='customer')>عميل</option><option value="order_manager" @selected($user->role==='order_manager')>مسؤول طلبات</option></select><button class="btn btn-soft btn-sm">حفظ</button></form></td><td><span class="status-badge {{ $user->is_active?'status-success':'status-danger' }}">{{ $user->is_active?'فعال':'موقوف' }}</span></td><td><form method="POST" action="{{ route('admin.users.toggle',$user) }}">@csrf @method('PATCH')<button class="btn btn-soft btn-sm" type="submit">{{ $user->is_active?'إيقاف':'تشغيل' }}</button></form></td></tr>
@empty<tr><td colspan="7" class="text-center text-secondary py-5">لا توجد نتائج.</td></tr>@endforelse
</tbody></table></div></div><div class="mt-4">{{ $users->links() }}</div>
@endsection
